apiVersion: v1
kind: Service
metadata:
  name: springboot-order-service-svc
spec:
  selector:
    app: springboot-order-service-ks
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort